services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=aliens'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql